server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb_analytics
    username: airbnb_user
    password: airbnb_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/airbnb

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
