server:
  port: 8082

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/airbnb_analytics
#    username: airbnb_user
#    password: airbnb_pass
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/airbnb
