server:
  port: 8082  # You can change this if 8080 is busy

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb_analytics
    username: airbnb_user
    password: airbnb_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Or "update" during dev to auto-create schema
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/airbnb
